stages:
  - build
  - deploy

variables:
  APP_NAME: ailead

build_and_export_to_mtr:
  environment:
    name: $CI_COMMIT_REF_NAME
  stage: build
  image:
    name: mtr.devops.telekom.de/caas/kaniko-project/executor:v1.23.1-debug
    entrypoint: [""]
  tags:
    - otc_run_sysbox_l
  before_script:
    # set auth data for MTR
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${MTR_DOCKER_REGISTRY}\":{\"username\":\"${MTR_REGISTRY_USER}\",\"password\":\"${MTR_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - umount /lib/modules/*
  script:
    # more info on k8s runners and kaniko executor here: https://docs.devops.telekom.de/documentation/mcicd/userdocumentation-magentacicd/kubernetes-runners-otc/
    - /kaniko/executor
      --registry-mirror dockerhub.devops.telekom.de
      --context $CI_PROJECT_DIR
      --dockerfile ./Dockerfile
      --destination $MTR_DOCKER_REGISTRY/ailead:latest
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg no_proxy=$no_proxy
      --cleanup
      --push-retry 3

deploy-to-EKS:
  stage: deploy
  image: mtr.devops.telekom.de/ai4coding/docker/ai4c-deployment-container:latest
  environment: dev
  tags:
    - aws_run_k8s_intel_s
  before_script:
    - docker login -u=$CI_REGISTRY_USER_AI4C -p=$CI_REGISTRY_PASSWORD_AI4C mtr.devops.telekom.de
  script:
    - helm version
    - pwd
    - ls -la helm/
    - helm lint $CI_PROJECT_DIR/helm/
    - >
      helm upgrade
      --install $APP_NAME $CI_PROJECT_DIR/helm
      --namespace "development"
      --set image.pullPolicy=Always
