version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.supervisor
    ports:
      - "3000:3000"  # Web server
      - "9090:9090"  # Monitoring
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      # Add any additional environment variables needed by your app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
