apiVersion: v1
kind: Service
metadata:
  name: { { include "ailead.fullname" . } }
  labels: { { - include "ailead.labels" . | nindent 4 } }
spec:
  ports:
    - port: { { .Values.service.port } }
      targetPort: 5000
  selector: { { - include "ailead.selectorLabels" . | nindent 4 } }
  type: { { .Values.service.type } }
