paths:
  dataRoot: /home/bun/data
  config: /home/bun/data/config
  database: file:///home/bun/data/config/main.db
  archive: /home/bun/data/archive
  logs: /home/bun/data/logs
hashing:
  algorithm: sha256
  hmacKey: "1234567890123456789012345678901234567890123456789012345678901234"
auth:
  initCode: "1234567890"
  secret: "12345678901234567890123456789012"
  trustedOrigins:
    - http://localhost:3000
    - http://localhost:4173
    - http://localhost:5173
  trustedProviders:
    - gitlab
    - jira
  allowDifferentEmails: true
  admins:
    - email: admin@admin.org
  providers:
    gitlab:
      baseUrl: https://gitlab.devops.de
      tokenUrl: https://gitlab.devops.de/oauth/token
      userInfoUrl: https://gitlab.devops.de/oauth/userinfo
      authorizationUrl: https://gitlab.devops.de/oauth/authorize
      authorizationUrlParams:
      clientId: adfslkjasdfjasldfkjaflkdsfs
      clientSecret: asdfklfnsldfksdfl
      scopes:
        - read:jira-work
        - read:jira-user
        - read:me
        - read:account
      redirectURI: /api/auth/callback/gitlab
    jiracloud:
      baseUrl: https://api.atlassian.com
      tokenUrl: https://auth.atlassian.com/oauth/token
      authorizationUrl: https://auth.atlassian.com/authorize
      authorizationUrlParams:
        audience: api.atlassian.com
      scopes:
        - read:jira-work
        - read:jira-user
        - read:me
        - read:account
      redirectURI: /api/auth/oauth2/callback/jiracloud
      accessibleResourcesUrl: https://api.atlassian.com/oauth/token/accessible-resources
    jira:
      baseUrl: https://api.atlassian.com
      authorizationUrl: /authorize
      authorizationUrlParams:
        audience: api.atlassian.com
      tokenUrl: /oauth/token
      scopes:
        - read:jira-work
        - read:jira-user
        - read:me
        - read:account
      redirectURI: /api/auth/oauth2/callback/jira
      accessibleResourcesUrl: https://api.atlassian.com/oauth/token/accessible-resources