paths:
  dataRoot: /Users/philhennel/Code/copilot-survey
  config: /Users/philhennel/Code/copilot-survey/config
  database: file:///Users/philhennel/Code/copilot-survey/config/main.db
  archive: /Users/philhennel/Code/copilot-survey/archive
  logs: /Users/philhennel/Code/copilot-survey/logs
hashing:
  algorithm: sha256
auth:
  initCode: aVNEpnVwsutCH5sq4HGuQCyoFRFh7ifneoiZogrpV2EoLRsc
  secret: uSNW4nDBnR?uazM7ar8djL7muKe!?hT7uEeUbmCWU2LQcWT
  trustedOrigins:
    - http://localhost:3000
    - http://localhost:4173
    - http://localhost:5173
  trustedProviders:
    - gitlab
    - jira
  allowDifferentEmails: true
  admins:
    - email: hennel@uni-bremen.de
    - email: phil.hennel@outlook.com
  providers:
    gitlab:
      baseUrl: https://gitlab.com
      clientId: 46c74fb18e7b9636ce76080acbd5dbaf6b0d8fbdcc921effb68e85b65fe7ded6
      clientSecret: gloas-f97c9ddbc4f890863cfd0f0d55a223a37bc0c0b4048bd1ab9cbaa5beb7153e45
      scopes:
        - read:jira-work
        - read:jira-user
        - read:me
        - read:account
      redirectURI: http://localhost:5173/api/auth/callback/gitlab
    jiracloud:
      baseUrl: https://api.atlassian.com
      authorizationUrl: https://auth.atlassian.com/authorize
      authorizationUrlParams:
        audience: api.atlassian.com
      tokenUrl: https://auth.atlassian.com/oauth/token
      scopes:
        - read:jira-work
        - read:jira-user
        - read:me
        - read:account
      redirectURI: /api/auth/oauth2/callback/jiracloud
      accessibleResourcesUrl: https://api.atlassian.com/oauth/token/accessible-resources
    jira:
      baseUrl: https://api.atlassian.com
      authorizationUrl: /authorize
      authorizationUrlParams:
        audience: api.atlassian.com
      tokenUrl: /oauth/token
      scopes:
        - read:jira-work
        - read:jira-user
        - read:me
        - read:account
      redirectURI: /api/auth/oauth2/callback/jira
      accessibleResourcesUrl: https://api.atlassian.com/oauth/token/accessible-resources
