replicaCount: 1

image:
  repository: mtr.devops.telekom.de/ai4coding/docker/ailead:latest
  pullPolicy: Always

service:
  name: ailead
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ailead.ai4c.aws.telekom.de
      path: /
      pathType: Prefix

imagePullSecrets:
  - name: ai4coding-mtr-pull-secret

securityContext:
  fsGroup: 1001
  supplementalGroups:
    - 1001
