name: build-docker

permissions:
  contents: read
  pages: write
  packages: write
  id-token: write
  attestations: write
  checks: write
  deployments: write

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  docker_build:
    strategy:
      matrix:
        data:
          - os: 'ubuntu-24.04'
            arch: 'amd64'
          - os: 'ubuntu-24.04-arm'
            arch: 'arm64'
    runs-on: ${{ matrix.data.os }}
    outputs:
      tags: ${{ join(steps.gen_output.outputs.*, ',') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - uses: actions/cache@v4
#        with:
#          path: |
#            ~/.bun/install/cache
#          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: metaarch
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
            suffix=-${{ matrix.data.arch }}
          images: |
            phennel/copilot-study
            ghcr.io/p-hennel/copilot-study
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr,
            type=edge,branch=main,
            type=sha,

      - name: Generate output
        id: gen_output
        run: |
          tags="${{ join(fromJSON($DOCKER_METADATA_OUTPUT_JSON).tags, ',') }}"
          arch="${{ matrix.data.arch }}"
          echo "tags_${arch}=${tags}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: $DOCKER_METADATA_OUTPUT_LABELS
          labels: $DOCKER_METADATA_OUTPUT_ANNOTATIONS
          sbom: true
          provenance: false
          outputs: type=registry,oci-mediatypes=true,oci-artifact=true
          # provenance: mode=max

      - name: Shoutrrr
        uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.SHOUTRRR_URL }}
          title: Built and pushed phennel/copilot-study (${{ matrix.data.arch }})
          message: $DOCKER_METADATA_OUTPUT_LABELS

  manifest_merge:
    runs-on: ubuntu-24.04
    needs: [docker_build]
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
          images: |
            phennel/copilot-study
            ghcr.io/p-hennel/copilot-study
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
          inputs: ${{ join(fromJSON(steps.meta.outputs.json).tags, ',') }}
          images: ${{ needs.docker_build.outputs }}
          push: true
